apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: easyshop
spec:
  template:
    spec:
      containers:
      - name: migration
        image: subhanshu12/e-shop-migration:3
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/easyshop"
        - name: CDN_URL
          valueFrom:
            configMapKeyRef:
              name: easyshop-config
              key: CDN_URL
      restartPolicy: OnFailure
